# 시스템 설정
system:
  version: "1.0.0"
  timezone: "Asia/Seoul"
  log_level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
# API 설정
api:
  exchange: "binance"
  # 실제 API 키는 환경 변수에서 로드됨
  # API_KEY: KEYNuQYIUnhQbxisT5CxOIqfTkjEp45RV0spU5Z1RSpKvr0nY9jpkpbKRZgIbJqeYzq
  # API_SECRET: IhVkkCPKPipVsE9YYlcaqueFihp6AysWajXrfARATu8xxVwdiLtgXT0gYGBYPvTQ
  testnet: false  # 테스트넷 사용 여부
  rate_limit: 1200  # API 요청 제한 (ms)
# 데이터 설정
data:
  symbols:
    - "BTC/USDT"
    - "ETH/USDT"
  timeframes:
    - "1m"
    - "5m"
    - "15m"
    - "1h"
    - "4h"
    - "1d"
  storage:
    path: "data_storage"
    format: "parquet"
    backup_enabled: true
    backup_interval: "1d"
# 거래 설정
trading:
  default_strategy: "integrated_strategy"  # 통합 전략으로 변경
  cooldown_period: 300  # 초 단위
  max_open_positions: 3
  position_sizing:
    method: "percentage"  # fixed에서 percentage로 변경
    initial_entry: 0.07   # 첫 진입 시 자본의 7%
    second_entry: 0.13    # 두 번째 진입 시 자본의 13% (총 20%)
    third_entry: 0.40     # 세 번째 진입 시 자본의 40% (총 60%)
# 리스크 관리
risk_management:
  capital_ratio: 0.1  # 전체 자본의 10%만 사용
  max_daily_loss: 0.05  # 일일 최대 손실 비율 15%로 증가
  max_weekly_loss: 0.25  # 주간 최대 손실 비율 25%로 설정
  consecutive_losses: 3   # 연속 손실 3회까지 허용
  cooldown_after_consecutive_losses: 360  # 연속 손실 후 6시간 대기 (분 단위)
  stop_loss:
    percentage: 1.0
    trailing: true
    activation_percentage: 1.0
  take_profit:
    percentage: 4.0
    trailing: true
    activation_percentage: 2.0
  leverage: 2  # 레버리지 설정
# 전략 설정
strategies:
  integrated_strategy:
    enabled: true
    trend_detection:
      short_ma_period: 20
      long_ma_period: 60
    fibonacci:
      use_levels: [0.382, 0.5, 0.618, 0.786]
      primary_entry_levels: [0.5, 0.618]  # 주요 진입 레벨
    stochastic:
      k_period: 14
      d_period: 3
      slowing: 3
      oversold_threshold: 20
      overbought_threshold: 80
    trendline:
      min_touches: 3  # 최소 3번의 터치 요구
      swing_period: 5
    signal_strength:
      min_threshold: 2  # 최소 2개 이상의 신호가 일치해야 함
# 알림 설정
notification:
  telegram:
    enabled: true
    bot_token: "8109411532:AAEQKzyLPf1RijphfuBmtmEPE9Cs6a4qqGI"
    chat_id: "7400895972"
  alerts:
    trade_execution: true
    position_update: true
    error_notification: true
    daily_summary: true
# 백테스트 설정
backtest:
  start_date: "2024-01-01"
  end_date: "2024-03-31"
  initial_balance: 10000  # USDT
  commission:
    maker: 0.0004  # 0.04%
    taker: 0.0004  # 0.04%
  slippage: 0.001  # 0.1%
  results:
    save_path: "backtest_results"
    save_format: "json"
    plot_enabled: true