# 시스템 설정
system:
  version: "1.0.0"
  timezone: "Asia/Seoul"
  log_level: "INFO"

# 거래소 설정
exchange:
  name: "binance"
  testnet: true
  rate_limit: 1200

# 거래 설정
trading:
  initial_capital: 10000.0
  leverage: 2
  position_size: 0.1
  max_open_positions: 3
  cooldown_period: 300

# 리스크 관리
risk_management:
  capital_ratio: 0.1
  max_daily_loss: 0.15
  max_weekly_loss: 0.25
  stop_loss:
    percentage: 2.0
    trailing: true
  take_profit:
    percentage: 4.0
    trailing: true

# 알림 설정
notification:
  telegram:
    enabled: true
    # 실제 봇 토큰과 채팅 ID는 환경 변수에서 로드됨
  alerts:
    trade_execution: true
    position_update: true
    error_notification: true
    daily_summary: true 