# 볼린저밴드 + RSI 전략
bollinger_rsi_strategy:
  # 볼린저밴드 설정
  bollinger:
    period: 20  # 이동평균 기간
    std_dev: 2.0  # 표준편차 승수
    source: "close"  # 가격 데이터 소스 (open, high, low, close)
  
  # RSI 설정
  rsi:
    period: 14  # RSI 계산 기간
    overbought: 70  # 과매수 기준
    oversold: 30  # 과매도 기준
    source: "close"  # 가격 데이터 소스
  
  # 진입 조건
  entry:
    long:
      conditions:
        - "price_below_lower_band"  # 가격이 하단밴드 아래
        - "rsi_oversold"  # RSI 과매도
        - "volume_increase"  # 거래량 증가
      required_conditions: 2  # 필요한 조건 수
    
    short:
      conditions:
        - "price_above_upper_band"  # 가격이 상단밴드 위
        - "rsi_overbought"  # RSI 과매수
        - "volume_increase"  # 거래량 증가
      required_conditions: 2  # 필요한 조건 수
  
  # 청산 조건
  exit:
    long:
      take_profit:
        - type: "fixed"  # 고정 익절
          percentage: 2.0
        - type: "trailing"  # 트레일링 익절
          percentage: 1.5
          activation: 1.0
      stop_loss:
        - type: "fixed"  # 고정 손절
          percentage: 1.0
        - type: "trailing"  # 트레일링 손절
          percentage: 0.5
          activation: 0.5
      additional:
        - condition: "price_above_upper_band"  # 상단밴드 돌파
          type: "partial"  # 부분 청산
          percentage: 0.5  # 50% 청산
    
    short:
      take_profit:
        - type: "fixed"
          percentage: 2.0
        - type: "trailing"
          percentage: 1.5
          activation: 1.0
      stop_loss:
        - type: "fixed"
          percentage: 1.0
        - type: "trailing"
          percentage: 0.5
          activation: 0.5
      additional:
        - condition: "price_below_lower_band"
          type: "partial"
          percentage: 0.5

# 오더블럭 + BOS 전략 (향후 구현)
orderblock_bos_strategy:
  # 기본 설정
  swing:
    period: 20  # 스윙 고점/저점 탐색 기간
    min_size: 0.5  # 최소 스윙 크기 (%)
  
  # 오더블럭 설정
  orderblock:
    lookback: 100  # 탐색 기간 (봉 수)
    min_size: 0.3  # 최소 오더블럭 크기 (%)
    max_size: 3.0  # 최대 오더블럭 크기 (%)
    volume_factor: 1.5  # 거래량 승수
  
  # BOS (Break of Structure) 설정
  bos:
    confirmation_candles: 3  # 확인 봉 수
    volume_confirmation: true  # 거래량 확인 필요
    min_breakout_size: 0.5  # 최소 돌파 크기 (%)
  
  # 진입 조건 (향후 구현)
  entry:
    long:
      conditions: []  # 구현 예정
    short:
      conditions: []  # 구현 예정
  
  # 청산 조건 (향후 구현)
  exit:
    long:
      conditions: []  # 구현 예정
    short:
      conditions: []  # 구현 예정 