name: Continuous Deployment

on:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t yourusername/crypto-trading-bot:latest .
          docker push yourusername/crypto-trading-bot:latest

      - name: Deploy to production
        run: |
          ssh user@yourserver "docker pull yourusername/crypto-trading-bot:latest && docker-compose up -d"
