# API 키 설정
BINANCE_API_KEY = "your_api_key"
BINANCE_API_SECRET = "your_api_secret"

# 데이터베이스 설정
DB_HOST = "your_db_host"
DB_PORT = "5432"
DB_NAME = "your_db_name"
DB_USER = "your_db_user"
DB_PASSWORD = "your_db_password" 